#!/bin/bash

. netlab_lib

NETLAB_NODES="r1 r2 r1n1 r1n2 r2n1 r2n2"

net_def() {
	if_dummy r1   d1 10.1.0
	if_dummy r1n1 d1 10.1.1
	if_dummy r1n2 d1 10.1.2
	if_dummy r2   d1 10.2.0
	if_dummy r2n1 d1 10.2.1
	if_dummy r2n2 d1 10.2.2

	if_veth r1 r2 10.10.1

	if_bridge    br0 10.3.0.1
	if_plug r1   br0 10.3.0.2
	if_plug r1n1 br0 10.3.0.3
	if_plug r1n2 br0 10.3.0.4

	if_bridge    br1 10.3.1.1
	if_plug r2   br1 10.3.1.2
	if_plug r2n1 br1 10.3.1.3
	if_plug r2n2 br1 10.3.1.4

	nl_netns send
	if_veth send r1n1 10.3.2
	nl_route send 224.0.0.0/4 dev veth-r1n1

	nl_netns recv
	if_veth recv r2n2 10.3.3
	nl_route recv 224.0.0.0/4 dev veth-r2n2
}

net_up() {
	. netlab_net_up
	NODES=$NETLAB_NODES
	netlab_each nl_netns
	net_def
}

net_down() {
	. netlab_net_down
	NODES=$NETLAB_NODES
	netlab_each nl_netns
	net_def
}

start() {
	NODES=${*:-$NETLAB_NODES}
	netlab_each netlab_node_start
}

stop() {
	NODES=${*:-$NETLAB_NODES}
	netlab_each netlab_node_stop
}

command_all() {
	NODES=$NETLAB_NODES
	netlab_each netlab_node_command $*
}

edit() {
	files=""
	NODES=${*:-$NETLAB_NODES}
	for N in $NODES
	do
		file="cfg/bird4_$N.conf"
		files="$files $file"
	done
	vim -p $files
}

log() {
	N=$1
	less node-$N/bird4.log
}

client() {
	N=$1
	../birdc -s node-$N/bird.sock $*
}

dump() {
	client $1 dump protocols
}

restart() {
	stop $*
	start $*
}

$*
